const colors = [
	'Alice Blue',
	'Antique White',
	'Aqua',
	'Aquamarine',
	'Azure',
	'Beige',
	'Bisque',
	'Black',
	'Blanched Almond',
	'Blue',
	'Blue Violet',
	'Brown',
	'Burly Wood',
	'Cadet Blue',
	'Chartreuse',
	'Chocolate',
	'Coral',
	'Cornflower Blue',
	'Cornsilk',
	'Crimson',
	'Cyan',
	'Dark Blue',
	'Dark Cyan',
	'Dark Golden Rod',
	'Dark Gray',
	'Dark Green',
	'Dark Khaki',
	'Dark Magenta',
	'Dark Olive Green',
	'Dark Orange',
	'Dark Orchid',
	'Dark Red',
	'Dark Salmon',
	'Dark Sea Green',
	'Dark Slate Blue',
	'Dark Slate Gray',
	'Dark Turquoise',
	'Dark Violet',
	'Deep Pink',
	'Deep Sky Blue',
	'Dim Gray',
	'Dodger Blue',
	'Fire Brick',
	'Floral White',
	'Forest Green',
	'Fuchsia',
	'Gainsboro',
	'GhostWhite',
	'Gold',
	'Golden Rod',
	'Gray',
	'Green',
	'Green Yellow',
	'Honey Dew',
	'Hot Pink',
	'Indian Red',
	'Indigo',
	'Ivory',
	'Khaki',
	'Lavender',
	'Lavender Blush',
	'Lawn Green',
	'Lemon Chiffon',
	'Light Blue',
	'Light Coral',
	'Light Cyan',
	'Light Golden Rod Yellow',
	'Light Green',
	'Light Grey',
	'Light Pink',
	'Light Salmon',
	'Light Sea Green',
	'Light Sky Blue',
	'Light Slate Gray',
	'Light Steel Blue',
	'Light Yellow',
	'Lime',
	'Lime Green',
	'Linen',
	'Magenta',
	'Maroon',
	'Medium Aqua Marine',
	'Medium Blue',
	'Medium Orchid',
	'Medium Purple',
	'Medium Sea Green',
	'Medium Slate Blue',
	'Medium Spring Green',
	'Medium Turquoise',
	'Medium Violet Red',
	'Midnight Blue',
	'Mint Cream',
	'Misty Rose',
	'Moccasin',
	'Navajo White',
	'Navy',
	'Old Lace',
	'Olive',
	'Olive Drab',
	'Orange',
	'Orange Red',
	'Orchid',
	'Pale Golden Rod',
	'Pale Green',
	'Pale Turquoise',
	'Pale Violet Red',
	'Papaya Whip',
	'Peach Puff',
	'Peru',
	'Pink',
	'Plum',
	'Powder Blue',
	'Purple',
	'Red',
	'Rosy Brown',
	'Royal Blue',
	'Saddle Brown',
	'Salmon',
	'Sandy Brown',
	'Sea Green',
	'Sea Shell',
	'Sienna',
	'Silver',
	'SkyBlue',
	'Slate Blue',
	'Slate Gray',
	'Snow',
	'Spring Green',
	'Steel Blue',
	'Tan',
	'Teal',
	'Thistle',
	'Tomato',
	'Turquoise',
	'Violet',
	'Wheat',
	'White',
	'White Smoke',
	'Yellow',
	'Yellow Green'
];
function formatColor(color) {
	if (!color) throw new Error('Argument for formatColors can not be falsy');

	return color.split(' ').join('');
}
export { colors, formatColor };
